import React, { useState, useEffect } from 'react';
import {
  DollarSign, Briefcase, TrendingUp, CheckCircle2, Copy, Download,
  Sparkles, ArrowRight, ShieldCheck, FileText, Info, HelpCircle
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import { useApp } from '../../context/AppContext';

export default function CTCOptimizer() {
  const { state } = useApp();
  const [ctc, setCtc] = useState(2400000);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    runOptimization(2400000, true);
  }, []);

  async function runOptimization(targetCtc = ctc, isSample = false) {
    setLoading(true);
    try {
      const res = await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/ctc/optimize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ctc: Number(targetCtc), isSample }),
      });
      const data = await res.json();
      if (data.success) {
        setResult(data.data);
      }
    } catch (e) {
      console.error('CTC optimization failed:', e);
    } finally {
      setLoading(false);
    }
  }

  function handleCopyDeclaration() {
    if (!result) return;
    const text = `
To: Payroll & HR Department
Subject: CTC Restructuring Declaration under Section 80CCD(2) & Flexi-Allowances

Dear Payroll Team,
I would like to optimize my CTC structure for FY 2026-27 to legally minimize TDS deductions:

1. Corporate NPS: Allocate 10% of Basic Salary (₹${result.optimized.corporateNPS.toLocaleString('en-IN')}/yr) towards Employer NPS contribution under Section 80CCD(2).
2. Telephone & Internet Reimbursement: Allocate ₹${(36000).toLocaleString('en-IN')}/yr against actual bills under Rule 3(7)(ix).
3. Food Card Allowance: Allocate ₹${(26400).toLocaleString('en-IN')}/yr via digital meal card.
4. Books & Periodicals: Allocate ₹${(24000).toLocaleString('en-IN')}/yr under Section 10(14)(i).

Please adjust my monthly payroll breakdown accordingly.

Best regards,
${state.consumer?.user?.name || 'Employee'}
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  }

  function downloadDeclarationPDF() {
    if (!result) return;
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(99, 102, 241);
    doc.text('FORMAL CTC RESTRUCTURING REQUEST', 20, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by FinAgent Tax Intelligence · Date: ${new Date().toLocaleDateString('en-IN')}`, 20, 30);

    doc.setDrawColor(226, 232, 240);
    doc.line(20, 36, 190, 36);

    let y = 48;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text('Employee Declaration & Payroll Instructions:', 20, y);
    y += 10;

    const lines = [
      `Employee Name: ${state.consumer?.user?.name || 'Salaried Taxpayer'}`,
      `Annual Cost to Company (CTC): ₹${Number(ctc).toLocaleString('en-IN')}`,
      `Total Annual Tax Savings Generated: ₹${result.annualTaxSaved.toLocaleString('en-IN')}`,
      `Monthly In-Hand Increase: +₹${result.monthlyInHandIncrease.toLocaleString('en-IN')}/month`,
      '',
      'Requested Component Adjustments:',
      `1. Section 80CCD(2) Corporate NPS (10% of Basic): ₹${result.optimized.corporateNPS.toLocaleString('en-IN')}`,
      `2. Telephone & Internet Allowance: ₹36,000`,
      `3. Meal Card Allowance: ₹26,400`,
      `4. Books & Periodicals: ₹24,000`,
      `Remaining Adjusted Special Allowance: ₹${result.optimized.specialAllowance.toLocaleString('en-IN')}`,
    ];

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    lines.forEach(l => {
      doc.text(l, 20, y);
      y += 7;
    });

    doc.save(`CTC_Tax_Declaration_${ctc}.pdf`);
  }

  const formatINR = (n) => '₹' + Number(n || 0).toLocaleString('en-IN');

  return (
    <div className="page-enter" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem', marginBottom: '0.25rem' }}>
            <span style={{ fontSize: '1.75rem' }}>💼</span>
            <h1 className="text-h1">AI CTC & Salary Tax Structuring Engine</h1>
          </div>
          <p className="text-sm text-secondary">
            Re-engineer your salary breakdown to legally slash TDS deductions. Unlocks Section 80CCD(2) Corporate NPS and tax-exempt flexi perks.
          </p>
        </div>

        <button
          onClick={() => { setCtc(2400000); runOptimization(2400000, true); }}
          className="btn btn-ghost btn-sm"
          style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)' }}
        >
          <Sparkles size={14} /> Try Sample ₹24 LPA Tech CTC
        </button>
      </div>

      {/* CTC Input Card */}
      <div className="card" style={{ padding: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ flex: 1, minWidth: 260 }}>
            <label className="text-xs text-muted" style={{ textTransform: 'uppercase' }}>Annual Cost to Company (CTC)</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginTop: 4 }}>
              <span style={{ fontSize: '1.75rem', fontWeight: 800, fontFamily: 'Space Grotesk', color: 'var(--primary)' }}>
                {formatINR(ctc)}
              </span>
              <span className="text-xs text-secondary">({(ctc / 100000).toFixed(1)} Lakhs per annum)</span>
            </div>
            <input
              type="range"
              min={600000}
              max={6000000}
              step={100000}
              value={ctc}
              onChange={e => {
                const val = Number(e.target.value);
                setCtc(val);
                runOptimization(val, false);
              }}
              style={{ width: '100%', marginTop: '0.75rem' }}
            />
          </div>

          <div style={{ display: 'flex', gap: '0.5rem' }}>
            {[1500000, 2400000, 3600000, 5000000].map(val => (
              <button
                key={val}
                onClick={() => { setCtc(val); runOptimization(val, false); }}
                className={`btn btn-sm ${ctc === val ? 'btn-primary' : 'btn-ghost'}`}
                style={{ fontSize: '0.75rem' }}
              >
                ₹{(val / 100000).toFixed(0)}L
              </button>
            ))}
          </div>
        </div>
      </div>

      {result && (
        <>
          {/* Top Big Callout Banner */}
          <div className="card" style={{
            background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.12), var(--surface))',
            border: '1px solid rgba(16, 185, 129, 0.3)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: '1.25rem'
          }}>
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '0.2rem 0.6rem', background: 'rgba(16, 185, 129, 0.2)', color: 'var(--green)', borderRadius: 20, fontSize: '0.75rem', fontWeight: 700, marginBottom: '0.5rem' }}>
                <CheckCircle2 size={14} /> SALARY RE-ENGINEERING OPTIMIZED
              </div>
              <div className="text-xs text-secondary">Extra Take-Home In-Hand Salary:</div>
              <div style={{ fontSize: '2.5rem', fontWeight: 900, fontFamily: 'Space Grotesk', color: 'var(--green)', margin: '0.25rem 0' }}>
                +{formatINR(result.monthlyInHandIncrease)} <span style={{ fontSize: '1.1rem', fontWeight: 500, color: 'var(--text-muted)' }}>/ month</span>
              </div>
              <div className="text-xs text-muted">
                Total Annual Tax Slashed: <strong style={{ color: 'var(--green)' }}>{formatINR(result.annualTaxSaved)}</strong> legally recovered from TDS.
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', minWidth: 240 }}>
              <button
                onClick={handleCopyDeclaration}
                className="btn btn-primary"
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', padding: '0.75rem 1rem' }}
              >
                <Copy size={16} /> {copied ? '✓ Copied to Clipboard!' : 'Copy HR Declaration Text'}
              </button>
              <button
                onClick={downloadDeclarationPDF}
                className="btn btn-ghost btn-sm"
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
              >
                <Download size={14} /> Download Declaration Form (PDF)
              </button>
            </div>
          </div>

          {/* Before vs After Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1rem' }}>
            {/* Standard HR Default */}
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                <h3 className="text-h3">Current Corporate Default</h3>
                <span className="badge badge-surface">Unoptimized</span>
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8125rem' }}>
                <tbody>
                  {[
                    ['Basic Salary (40%)', formatINR(result.current.basic)],
                    ['House Rent Allowance (HRA)', formatINR(result.current.hra)],
                    ['Employer PF (12%)', formatINR(result.current.employerPF)],
                    ['Corporate NPS 80CCD(2)', '₹0 (Missed Opportunity)'],
                    ['Flexi Perks (Phone/Food/Books)', '₹0 (Taxed at 30%)'],
                    ['Taxable Special Allowance', formatINR(result.current.specialAllowance)],
                    ['---', '---'],
                    ['Total Annual Income Tax (TDS)', formatINR(result.current.annualTax)],
                    ['Monthly In-Hand Take Home', formatINR(result.current.monthlyInHand)],
                  ].map(([label, val], idx) => label === '---' ? (
                    <tr key={idx}><td colSpan={2} style={{ borderBottom: '1px solid var(--glass-border)', padding: '0.25rem 0' }} /></tr>
                  ) : (
                    <tr key={idx} style={{ borderBottom: '1px solid var(--glass-border)22' }}>
                      <td style={{ padding: '0.5rem 0', color: idx >= 7 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: idx >= 7 ? 700 : 400 }}>{label}</td>
                      <td style={{ padding: '0.5rem 0', textAlign: 'right', fontFamily: 'Space Grotesk', fontWeight: idx >= 7 ? 800 : 600, color: idx === 7 ? 'var(--red)' : 'var(--text-primary)' }}>{val}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* AI Re-Structured Plan */}
            <div className="card" style={{ border: '1px solid rgba(16, 185, 129, 0.4)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                <h3 className="text-h3" style={{ color: 'var(--green)' }}>AI Re-Structured Structure</h3>
                <span className="badge badge-green">Zero Tax Waste</span>
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8125rem' }}>
                <tbody>
                  {[
                    ['Basic Salary (40%)', formatINR(result.optimized.basic)],
                    ['House Rent Allowance (HRA)', formatINR(result.optimized.hra)],
                    ['Employer PF (12%)', formatINR(result.optimized.employerPF)],
                    ['Corporate NPS 80CCD(2)', formatINR(result.optimized.corporateNPS)],
                    ['Flexi Perks (Phone/Food/Books)', formatINR(result.optimized.flexiAllowances)],
                    ['Adjusted Special Allowance', formatINR(result.optimized.specialAllowance)],
                    ['---', '---'],
                    ['Total Annual Income Tax (TDS)', formatINR(result.optimized.annualTax)],
                    ['Monthly In-Hand Take Home', formatINR(result.optimized.monthlyInHand)],
                  ].map(([label, val], idx) => label === '---' ? (
                    <tr key={idx}><td colSpan={2} style={{ borderBottom: '1px solid var(--glass-border)', padding: '0.25rem 0' }} /></tr>
                  ) : (
                    <tr key={idx} style={{ borderBottom: '1px solid var(--glass-border)22' }}>
                      <td style={{ padding: '0.5rem 0', color: idx >= 7 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: idx >= 7 ? 700 : 400 }}>{label}</td>
                      <td style={{ padding: '0.5rem 0', textAlign: 'right', fontFamily: 'Space Grotesk', fontWeight: idx >= 7 ? 800 : 600, color: idx >= 7 ? 'var(--green)' : 'var(--text-primary)' }}>{val}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* 4 Tax Saving Levers Breakdown */}
          <div className="card">
            <h3 className="text-h3" style={{ marginBottom: '1rem' }}>The 4 High-Alpha Tax Levers Employed</h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '0.875rem' }}>
              {result.breakdown.map((item, i) => (
                <div key={i} style={{ padding: '1rem', background: 'var(--surface-raised)', borderRadius: 'var(--radius)', border: '1px solid var(--glass-border)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                    <span className="badge badge-green" style={{ fontSize: '0.65rem' }}>+Save {formatINR(item.taxSaved)}</span>
                    <span style={{ fontFamily: 'Space Grotesk', fontWeight: 800, fontSize: '0.9rem' }}>{formatINR(item.annualDeduction)}</span>
                  </div>
                  <div style={{ fontWeight: 700, fontSize: '0.85rem', marginBottom: 4 }}>{item.benefit}</div>
                  <p className="text-xs text-secondary" style={{ lineHeight: 1.4 }}>{item.legalClause}</p>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
